### PR TITLE
[WIP] Adds the ability to load content from an URL

### PR DESCRIPTION
**Pull request by Potherca**
This pull-request addresses [issue 222 from the shellcheck repo](https://github.com/koalaman/shellcheck/issues/222).

It makes it possible to load content from an URL by adding `?url=http://example.com/path/to/script.sh` to the `https://www.shellcheck.net/` URL.

The PHP `file_get_contents` function is used to get the remote file. For that to work, [the  `allow_url_fopen` option must be enabled](http://php.net/manual/en/features.remote-files.php) in the PHP settings (usually `php.ini`). If that is not an option, I'll open another PR with an alternative option (cUrl, for instance).

This PR does _not_ add a `<input>` field to read the URL from. If that is desired I have no issue with adding more commits to the PR to implement it.

### CODE REVIEW

**Comment by Potherca** [comment]
If you're interested in the functionality, I don't mind making a less naive implementation.

I would need a more clearly defined context... 

Usually I'd grab Guzzle, as that makes it trivial to handle timeout and other transport options.

Regarding HTML frames, I honestly wouldn't bother. All of the more viable services have a link to a "raw" version of a snippet only containing the code. Regardless, if you feel HTML "de-framing" should be part of the functionality, I have some options I could implement.

As far as malicious proxying goes, I'm open to suggestions... Request limit? CAPTCHA? Many ways to solve that problem.

As stated, if you are up for accepting this functionality, I've got an interest in making it happen 😸

**Comment by koalaman** [comment]
I'm not entirely sure what the use case is. Will people paste a link to check their own content? Will they create a link to share with others? Will services integrate a "check with shellcheck" button? 

I already run an IRC bot on #bash@freenode which lets you check scripts by URL. It's rare for anyone to give it a raw link. People usually give it a pastebin or github link and expect it to work. I don't think ignoring frames is viable except for integration work (and in those cases I'm not sure I want the responsibility of hosting SaaS). 

In any case, any loading of cross-site resources needs to be disabled by default, cached appropriately, and be resilient to attacks on both the local and the remote host (including DoS). I imagine this is more work than the current site itself, but if someone can do it securely and robustly, I'd merge it.

PS: Earlier this week I too added a feature to auto-load content (used for IRC and ads dogfooding), sorry for the late merge.

**Comment by Potherca** [comment]
In my opinion the most likely scenario for people to use an URL feature would be to either quickly validate their own code (and not share the URL) or validate the code of others (and share the url).

If services will integrate a "check with shellcheck" button largely depends on how much use the URL feature will receive.

If your experience thus far is that users paste HTML framed links then it stands to reason that the feature must support "de-framing".

I agree that if such a feature is to be built it needs to be robust and secure. I have an acquaintance who specialises in security and enjoys contributing to FOSS. I'll get him on board to ensure that whatever gets implemented is as safe as possible. (I share your concerns for attack vectors, they are a very real threat).

As far as the "late merge" goes: no need for apologies. These things happen :-)

/cc: @brammittendorff

**Comment by brammittendorff** [comment]
@Potherca I agree with @koalaman that this implementation is trickier than it appears.

This includes Security, Hosting (traffic and such), Storage (heroku? or other free solution). Lets talk about this soon @Potherca maby we could make a great plan and present it to @koalaman .

For now i should not merge this PR, this is to risky.

**Pull request closed without merging**
